[project]
name = "graphwiz-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diagrams>=0.24.1",
    "fastapi[all]>=0.115.6",
    "graphviz[all]>=0.20.3",
]
